#!/usr/bin/env node
/**
 * cockpit-refresh.mjs — engine puller: project memory/events.jsonl into
 * <vault>/00_Dashboard/_data/calibration-*.md frontmatter notes that
 * Bases/Dataview render (the Calibration Board). Local-evidence only — fits the
 * review/analysis cadence contract (reads events.jsonl, writes projection notes).
 *
 * Overwrite-in-place, NO dated filenames, stale notes pruned. See COCKPIT_SPEC.md.
 *
 *   node run.mjs pull cockpit-refresh [--dry-run] [--as-of=YYYY-MM-DD]
 */

import { readFileSync, existsSync, mkdirSync, writeFileSync, readdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';

import { getEngineRoot } from '../lib/config.mjs';
import { today } from '../lib/markdown.mjs';

const HIT_LABELS = new Set(['Played out', 'Directionally right / poorly timed']);
const MISS_LABELS = new Set(['Noisy', 'Missed', 'Stale']);
const WINDOWS = [90, 180, 365];

function eventsPath() { return join(getEngineRoot(), '_state', 'events.jsonl'); }
function outDir() { return join(getEngineRoot(), '00_Dashboard', '_data'); }

function readEvents(path) {
  if (!existsSync(path)) return [];
  const out = [];
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const t = line.trim();
    if (!t) continue;
    try { out.push(JSON.parse(t)); } catch { /* tolerate partial line */ }
  }
  return out;
}

function daysBetween(aIso, bIso) {
  const a = Date.parse(aIso), b = Date.parse(bIso);
  if (Number.isNaN(a) || Number.isNaN(b)) return Infinity;
  return Math.abs(b - a) / 86_400_000;
}

function slug(s) {
  return String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function rollup(events, asOf) {
  const agents = [...new Set(events.map(e => e.agent ?? 'unknown'))].sort();
  const rows = [];
  for (const agent of agents) {
    const mine = events.filter(e => (e.agent ?? 'unknown') === agent);
    for (const w of WINDOWS) {
      const inWin = mine.filter(e => daysBetween(e.ts, asOf) <= w);
      if (!inWin.length) continue;
      const refuted = inWin.filter(e => e.type === 'refutation' && e.outcome === 'refuted').length;
      const survived = inWin.filter(e => e.type === 'refutation' && e.outcome === 'survived').length;
      const refTotal = refuted + survived;
      const graded = inWin.filter(e => e.type === 'outcome');
      const hits = graded.filter(e => HIT_LABELS.has(e.outcome)).length;
      const misses = graded.filter(e => MISS_LABELS.has(e.outcome)).length;
      const accDenom = hits + misses;
      rows.push({
        agent, window: `${w}d`, n: inWin.length, refuted, survived,
        refute_rate: refTotal ? Number((refuted / refTotal).toFixed(3)) : null,
        accuracy: accDenom ? Number((hits / accDenom).toFixed(3)) : null,
        brier: null,
      });
    }
  }
  return rows;
}

function noteBody(row, asOf) {
  return [
    '---', 'type: calibration-rollup', `agent: ${row.agent}`, `window: ${row.window}`,
    `n: ${row.n}`, `refuted: ${row.refuted}`, `survived: ${row.survived}`,
    `refute_rate: ${row.refute_rate ?? 'null'}`, `accuracy: ${row.accuracy ?? 'null'}`,
    `brier: ${row.brier ?? 'null'}`, `generated_at: ${asOf}`, 'source: events.jsonl', '---',
    '<!-- generated by `run pull cockpit-refresh` — do not edit; regenerate from events.jsonl -->', '',
  ].join('\n');
}

export async function pull(flags = {}) {
  const asOf = String(flags['as-of'] || today());
  const dir = outDir();
  const events = readEvents(eventsPath());
  const rows = rollup(events, asOf);
  const notes = rows.map(r => ({ file: `calibration-${slug(r.agent)}-${r.window}.md`, body: noteBody(r, asOf) }));
  const wanted = new Set(notes.map(n => n.file));

  let existing = [];
  if (existsSync(dir)) existing = readdirSync(dir).filter(f => f.startsWith('calibration-') && f.endsWith('.md'));
  const stale = existing.filter(f => !wanted.has(f));

  if (flags['dry-run']) {
    console.log(`[cockpit-refresh] dry-run: ${events.length} events → ${notes.length} notes, ${stale.length} stale (as-of ${asOf})`);
    return { ok: true, dryRun: true, notes: notes.length, stale: stale.length };
  }

  mkdirSync(dir, { recursive: true });
  for (const n of notes) writeFileSync(join(dir, n.file), n.body, 'utf8');
  for (const f of stale) rmSync(join(dir, f));
  console.log(`[cockpit-refresh] wrote ${notes.length} calibration notes, pruned ${stale.length} → ${dir}`);
  return { ok: true, written: notes.map(n => n.file), pruned: stale };
}
