/**
 * options-review.mjs — Manual options checklist scaffold for review queue candidates.
 *
 * Reads the latest Streamline Report sidecar and generates a pre-filled checklist
 * for manual Fidelity/broker verification. No broker execution is generated.
 *
 * Usage:
 *   node run.mjs pull options-review
 *   node run.mjs pull options-review --symbol TICKER
 *   node run.mjs pull options-review --all
 *   node run.mjs pull options-review --dry-run
 */

import { existsSync } from 'node:fs';
import { readdir, readFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { getPullsDir } from '../lib/config.mjs';
import { buildNote, buildTable, dateStampedFilename, today, writeNote } from '../lib/markdown.mjs';

const SIDECAR_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..', '.cache', 'orchestrator', 'streamline-reports');

export async function pull(flags = {}) {
  const targetSymbol = flags.symbol ? String(flags.symbol).toUpperCase() : null;
  const allMode = Boolean(flags.all);

  const sidecar = await loadLatestSidecar();
  if (!sidecar) {
    console.log('Options Review: no streamline report sidecar found. Run `node run.mjs pull streamline-report` first.');
    return { filePath: null, checklistCount: 0 };
  }

  let candidates = sidecar.review_items ?? [];

  if (targetSymbol) {
    candidates = candidates.filter(item =>
      item.title.toUpperCase().includes(targetSymbol) ||
      (item.signals ?? []).some(s => String(s).toUpperCase().includes(targetSymbol))
    );
  } else if (!allMode) {
    candidates = candidates.filter(item => ['alert', 'critical'].includes(item.signal_status));
  }

  if (!candidates.length) {
    const hint = targetSymbol
      ? `No candidates matched symbol ${targetSymbol}.`
      : 'No alert/critical candidates in the latest report. Use --all to include watch-level items.';
    console.log(`Options Review: ${hint}`);
    return { filePath: null, checklistCount: 0 };
  }

  console.log(`Options Review: building checklists for ${candidates.length} candidate(s)...`);

  const suffix = targetSymbol ? `Options_Review_${targetSymbol}` : 'Options_Review';
  const note = buildOptionsNote({ candidates, targetSymbol, reportDate: sidecar.date });
  const filePath = join(getPullsDir(), 'Market', dateStampedFilename(suffix));

  if (flags['dry-run']) {
    console.log(note);
  } else {
    writeNote(filePath, note);
    console.log(`Wrote: ${filePath}`);
  }

  return { filePath: flags['dry-run'] ? null : filePath, checklistCount: candidates.length };
}

function buildOptionsNote({ candidates, targetSymbol, reportDate }) {
  const checklistRows = candidates.map(item => [
    item.title,
    item.signal_status,
    item.edge_type ?? 'review required',
    item.disposition ?? 'Review',
    '[ ]',  // Spread < 5% of mid
    '[ ]',  // OI > 100
    '[ ]',  // Volume > 10
    '[ ]',  // IV vs HV checked
    '[ ]',  // No event in expiry window
    '[ ]',  // Max loss defined
    '[ ]',  // Permission level confirmed
    item.invalidation ?? '—',
  ]);

  return buildNote({
    frontmatter: {
      title: targetSymbol ? `Options Review — ${targetSymbol}` : 'Options Review — Batch',
      source: 'Vault Orchestrator',
      date_pulled: today(),
      report_date: reportDate ?? today(),
      domain: 'market',
      data_type: 'options_review',
      candidate_count: candidates.length,
      signal_status: candidates.some(i => ['alert', 'critical'].includes(i.signal_status)) ? 'watch' : 'clear',
      tags: ['options-review', 'manual-check', 'execution-quality'],
    },
    sections: [
      {
        heading: 'Operating Rule',
        content: [
          '> All fields must be verified manually in Fidelity Active Trader Pro or equivalent.',
          '> This checklist is a scaffold only — no broker execution is generated by this note.',
          '> Do not size a position without confirming spread, OI, event calendar, and max loss.',
        ].join('\n'),
      },
      {
        heading: 'Checklist',
        content: buildTable(
          ['Candidate', 'Status', 'Edge', 'Disposition', 'Sprd<5%', 'OI>100', 'Vol>10', 'IV/HV', 'NoEvent', 'MaxLoss', 'Perm', 'Invalidation'],
          checklistRows
        ),
      },
      {
        heading: 'Field Guide',
        content: [
          '- **Sprd<5%**: bid-ask spread must be < 5% of the mid price for acceptable fill quality.',
          '- **OI>100**: open interest at the target strike must exceed 100 contracts.',
          '- **Vol>10**: daily volume must exceed 10 contracts to confirm liquidity.',
          '- **IV/HV**: compare implied volatility to historical vol; avoid entries when IV is spiked.',
          '- **NoEvent**: confirm no earnings release, FDA decision, or macro event falls before expiry.',
          '- **MaxLoss**: define the maximum dollar loss before entering; must fit position sizing rules.',
          '- **Perm**: confirm the strategy level (long call, spread, etc.) is enabled in your account.',
        ].join('\n'),
      },
    ],
  });
}

async function loadLatestSidecar() {
  if (!existsSync(SIDECAR_DIR)) return null;
  let files;
  try {
    files = (await readdir(SIDECAR_DIR)).filter(f => f.endsWith('.json')).sort().reverse();
  } catch { return null; }
  if (!files.length) return null;
  try {
    return JSON.parse(await readFile(join(SIDECAR_DIR, files[0]), 'utf-8'));
  } catch { return null; }
}
